Create bi-nif.json
org-id/register pull request #438
Opened 2021-01-25 14:58 UTC by andreaszenasidi

2021-02-02 18:03 UTC, kd-ods requested changes
Just a few minor things to iron out. Otherwise looks good.

2021-02-02 18:03 UTC, kd-ods commented on lists/bi/bi-nif.json
> +    "guidanceOnLocatingIds": "The NIF number needs to be requested from the company or organisation. After obtaining the NIF number, the publicly available web page can be used to verify the ownershi
The same typo as above appears here.

2021-02-03 08:20 UTC, siwhitehouse commented on lists/bi/bi-nif.json
> +  "listType": "primary",
Yes, they should be secondary as per the description in the schema: "[Examples of secondary lists are VAT or Tax identifiers, or employer identification numbers](https://github.com/org-id/register/blob/master/schema/codelist-listType.json#L19)"

2021-02-05 13:10 UTC, kd-ods commented
@andreaszenasidi  - can you just confirm that you've made all the changes you want to make and that you're happy for us to re-review this now? (There's a 're-request review' button that you can use by our names in the 'Reviewers' section on the right-hand side.)

2021-02-05 14:11 UTC, andreaszenasidi commented
@kd-ods  Oh sorry, I was not aware of these steps. I confirm I made all the requested changes.

2021-02-09 11:47 UTC, kd-ods approved these changes
Looks good. Thanks, Andrea. I'll merge and update the org-id website.

2021-02-09 11:48 UTC, merged