Create za-sars.json
org-id/register pull request #450
Opened 2021-05-17 15:54 UTC by andreaszenasidi

Github issue https://github.com/org-id/register/issues/448

2021-06-03 10:17 UTC, kd-ods commented
@andreaszenasidi - you say in the description 'Businesses can receive multiple tax numbers such as CIT, VAT, PAYE etc'. Since that is the case, the guidance on locating (and recording IDs) isn't quite enough ("Ask the organisation you wish to identify to provide it's tax number"). We will need to suggest that the type of tax number is prefixed in a standard way onto the tax number, in order to create a unique id. I'm just looking for examples of where we've done this elsewhere, to give you a helping hand.

2021-06-03 11:19 UTC, kd-ods commented
Actually, @andreaszenasidi - I think we should follow the pattern set by @siwhitehouse when he added separate [org-id entries](http://org-id.guide/results?structure=all&coverage=KG&sector=all) for lists managed by the Ministry of Justice in the Kyrgyz Republic.

Practically, that means turning this entry into za-cit, I think. (Or whichever identifier it is that your publisher is going to use.) And making clear that the SARS is the issuer/manager of these IDs.

How does that sound?

2021-06-03 13:59 UTC, andreaszenasidi commented
@kd-ods thanks for the suggestion. I renamed the JSON to **za-cit** and made the necessary changes in the JSON itself as you requested. I hope it's good now.

2021-06-04 09:05 UTC, kd-ods requested changes
Couple of minor edits requested.

2021-06-04 09:05 UTC, kd-ods commented on lists/za/za-cit.json
> +    "guidanceOnLocatingIds": "Ask the organisation you wish to identify to provide it's Corporate Income Tax number, sometimes referred to as Income Tax number.",
spelling: "... provide its Corporate..."

2021-06-04 09:11 UTC, andreaszenasidi commented
@kd-ods I made all requested changes.

2021-06-04 09:42 UTC, kd-ods approved these changes

2021-06-04 10:31 UTC, merged