Create SUNAT
org-id/register pull request #452
Opened 2021-06-08 08:02 UTC by mrshll1001

Based on #451

2021-06-08 09:00 UTC, kd-ods requested changes
@mrshll1001, there are a couple of field-level changes that need to be made. (See specific comments). At a higher level: I think this list should be re-focused on the RUC number. By that, I mean, that the code should be pe-ruc and SUNAT should be referred to in the description as the body that curates the list. (Tax authorities can often end up administering several types of tax number, so refocusing like this future-proofs the entry a little.)

Also - the name of the file needs to be adjusted. It should be pe-xxxx.json

Give me a shout if you want to talk through any of the above.

2021-06-28 11:33 UTC, kd-ods commented
Hi @mrshll1001 - I reviewed this PR a while back. Let me know if you need any more assistance getting it over the line.

2021-06-30 10:11 UTC, kd-ods requested changes
A couple of final things needed, @mrshll1001.

2021-06-30 10:11 UTC, kd-ods commented on lists/pe/RUC.json
> +    "en": "National Superintendency of Customs and Tax Administration (Peru)",
I think we need:

"en": "RUC Number (Peru)"
"local": "Registro Único del Contribuyente (Perú)"

2021-06-30 10:11 UTC, kd-ods commented on lists/pe/RUC.json
> +    "en": "The 'Registro Único del Contribuyente' (RUC) number is an 11-digit tax ID number for any natural or legal person (such as a company) in Peru, and is provided and maintained by SUNAT. The S
If we remove 'Superintendencia Nacional de Aduanas y de Administración Tributaria' from the name of this list, then it should be added to the description here the first time 'SUNAT' is mentioned.

2021-06-30 10:11 UTC, kd-ods commented on lists/pe/RUC.json
> +  "code": "PE-SUNAT",
The code should be changed to PE-RUC.

Also, the name of the file needs to be changed to pe-ruc.json.

2021-07-12 09:13 UTC, mrshll1001 commented on lists/pe/SUNAT
> +  "confirmed": false,
Done

2021-07-14 13:06 UTC, kd-ods approved these changes
Looking good. I'll merge and deploy.

2021-07-14 13:08 UTC, merged