Create NTN
org-id/register pull request #461
Opened 2021-07-15 09:58 UTC by AudreyIATI

HI @kd-ods,

This is related to ongoing conversation [here](https://github.com/org-id/register/issues/441)

Please let me know if I need to do anything else.

Thanks,
Audrey

2021-08-19 20:05 UTC, kd-ods requested changes
Hi @AudreyIATI - there are a few things to look at here. It will probably be easiest for you to edit the file back in the editing app. I've added details of how to do that at the end of the Guidance doc.

2021-08-24 09:40 UTC, AudreyIATI commented on lists/PK/pk-ntn.json
> +    "en": "This list is a record from the Federal Board of Revenue, Government of Pakistan. It contains active, blacklisted and exempt Taxpayer Lists based on the National Tax Number (NTN) of organis
Done!

2021-08-24 09:41 UTC, AudreyIATI commented on lists/PK/pk-ntn.json
> +  "structure": [
Done!

2021-08-24 09:41 UTC, AudreyIATI commented on lists/PK/pk-ntn.json
> +    "humantiarian_relief"
Done!

2021-08-24 09:41 UTC, AudreyIATI commented on lists/PK/pk-ntn.json
> +  "listType": "primary",
Done!

2021-08-24 10:02 UTC, AudreyIATI commented on lists/PK/pk-ntn.json
> +      "pdf"
The ATL output gives a pitiful amount of information (shown below), the bulk export provides an Excel sheet with every registered NTN, but no additional information beyond the below.

Registration No
Organisation name
Business name
Filing status
Filing status checking date

2021-08-24 10:14 UTC, AudreyIATI commented
Hi @kd-ods = changes made, and new json pasted over the old.
Let me know if I need to change/correct anything.

Thanks!
Audrey

2021-09-24 11:39 UTC, AudreyIATI commented
Hi @kd-ods - checking to see if there's any update on this?

2021-09-24 16:08 UTC, kd-ods approved these changes
This looks great, Audrey. I realise it took some time for me to get to this. Thanks for your patience.

I'll merge this and update the website now.

2021-09-24 16:09 UTC, merged

2021-10-07 08:43 UTC, AudreyIATI commented
No worries @kd-ods - Thank you for all your help!