Create BF-MATD
org-id/register pull request #472
Opened 2021-11-16 12:25 UTC by AudreyIATI

2021-12-03 17:27 UTC, kd-ods requested changes
Hi @AudreyIATI - there's a few things to update here. Also, the name of the file, instead of BF-MATD, needs to be bf-matd.json.

Thanks!

2021-12-03 17:27 UTC, kd-ods commented on lists/BF-MATD
> +    "government_agency"
This list seems to cover CSOs, not government departments and ministries. So I think this value should be 'charity'

2021-12-03 17:27 UTC, kd-ods commented on lists/BF-MATD
> +      "pdf"
Since none of this information is available online, I think availability should be empty and not contain 'PDF'.

So:

"availability": []

2021-12-03 17:27 UTC, kd-ods commented on lists/BF-MATD
> +    "features": [
Since none of this information is available online, I think features should be empty.

So:

"features": []

2021-12-03 17:30 UTC, kd-ods commented
@AudreyIATI - one more thing that I just noticed. The place for this file is in the 'bf' directory in the the 'lists' directory, so ultimately:

lists/bf/bf-matd.json

2021-12-03 17:33 UTC, kd-ods commented on lists/BF-MATD
> +      "pdf"
Actually, make that:

    "availability": [
      "data_not_available"
    ]

2021-12-10 15:07 UTC, AudreyIATI commented
Changes made @kd-ods - let me know if I need to do anything further.

2021-12-20 15:56 UTC, kd-ods approved these changes
Great. I'll approve, merge and deploy this now.

2021-12-20 15:57 UTC, merged

2021-12-21 11:06 UTC, AudreyIATI commented
Thank you Kadie!