Create TN-RNE
org-id/register pull request #479
Opened 2021-12-02 15:53 UTC by AudreyIATI

Linked to issue #478

2021-12-03 17:45 UTC, kd-ods requested changes
This just needs a few little edits. Plus the name and location of the file need to be changed, to:

lists/tn/tn-rne.json

Thanks, @AudreyIATI!

2021-12-03 17:45 UTC, kd-ods commented on lists/TN-RNE
> +    "en": "The National Register of Companies",
Maybe edit this to "The National Register of Companies, Tunisia"

Or "Tunisian National Register of Companies"

2021-12-03 17:45 UTC, kd-ods commented on lists/TN-RNE
> +    "onlineAccessDetails": null,
For onlineAccessDetails you could add something like "Individual records can be found via the search form. For bulk downloads, there's a fee to pay."

2021-12-03 17:45 UTC, kd-ods commented on lists/TN-RNE
> +    "lastUpdated": "2020"
lastUpdated can probably be 2021-12-06 or something.

2021-12-08 10:08 UTC, AudreyIATI commented
Thanks for taking a look Kadie.

Changes made - let me know if I need to change anything else.

Audrey

2021-12-20 16:26 UTC, kd-ods approved these changes
I'll approve, merge and deploy now.

2021-12-20 16:26 UTC, merged

2021-12-21 11:06 UTC, AudreyIATI commented
Thank you Kadie!