Create CH-BS
org-id/register pull request #502
Opened 2022-03-25 11:12 UTC by AudreyIATI

Related to [Issue 501](https://github.com/org-id/register/issues/501)

2022-04-01 11:01 UTC, kd-ods requested changes
There are a few things to amend here.

2022-04-01 11:01 UTC, kd-ods commented on lists/ch/ch-bs-cr.json
> +  "code": "CH-BS",
Please change this to CH-BS-CR. (I've already edited the filename and directory to match this.)

2022-04-04 10:58 UTC, AudreyIATI commented
Changes made - let me know if I missed anything.

Thanks,
Audrey

2022-04-19 08:23 UTC, kd-ods approved these changes

2022-04-19 08:24 UTC, merged

2022-04-20 09:37 UTC, andylolz commented
It looks like this is the only code to contain more than one hyphen. I wonder if the second hyphen could be replaced by an underscore? I.e. `CH-BS_CR`. It looks like that’s the approach taken with other codes (e.g. `AE-RK_CR`; `BE-BCE_KBO`; `CA-CRA_ACR` etc).

I checked [the guidance](http://docs.org-id.guide/en/latest/metadata/#list-name-code), and it doesn’t look like there’s anything to say a hyphen shouldn’t be used in either part of the code. But hyphens are used to separate the two parts of the register code, as well as to separate the two parts of the organisation ID that these codes are used in. Adding additional hyphens makes it ambiguous as to which part of the code is which.

2022-04-20 14:59 UTC, kd-ods commented
Thanks @andylolz - I'll take a look at this. I get the point about ambiguous separability.

2022-04-22 11:29 UTC, kd-ods commented
@andylolz - I'm proposing this [edit to the org-id handbook](https://github.com/org-id/handbook/pull/25) which would mean changing this particular org list code to CH_BS-CP. Does that look OK to you? Do comment on the handbook PR if that's more fitting.

2022-04-22 11:29 UTC, kd-ods commented
@andylolz - I'm proposing this [edit to the org-id handbook](https://github.com/org-id/handbook/pull/25) which would mean changing this particular org list code to CH_BS-CP. Does that look OK to you? Do comment on the handbook PR if that's more fitting.

2022-04-22 12:21 UTC, andylolz commented
> which would mean changing this particular org list code to CH_BS-CP. Does that look OK to you?

@kd-ods Aha! Good catch – my underscore was misplaced! This is great, thanks. Fully support this proposal.

Thanks also for creating and linking to the proposed handbook edit – the explanation in your PR is really clear.