Create TH-MOI
org-id/register pull request #504
Opened 2022-03-25 16:09 UTC by AudreyIATI

Related to [Issue 503](https://github.com/org-id/register/issues/503)

2022-04-01 09:00 UTC, kd-ods requested changes
A few things to address before we can merge this.

2022-04-01 09:00 UTC, kd-ods commented on lists/th/th-moi.json
> +    "lastUpdated": "25/03/22"
Please put the date in YYYY-MM-DD format

2022-04-04 11:09 UTC, AudreyIATI commented
Changes made - let me know if you need anything else from me.

Thanks,
Audrey

2022-04-12 13:16 UTC, amy-silcock commented
Let me know if there are further items to change on this. As well as what needs to be changed so all checks pass.

2022-04-12 14:46 UTC, merged