Create CI-MOI
org-id/register pull request #506
Opened 2022-03-25 16:29 UTC by AudreyIATI

Related to [issue 505](https://github.com/org-id/register/issues/505)

2022-04-01 08:45 UTC, kd-ods requested changes
There are a few things to correct here. And the directory and filename need to be altered. At the moment it's: lists/CI-MOI. But it needs to be lists/ci/ci-moi.json

Thanks!

2022-04-01 08:45 UTC, kd-ods commented on lists/CI-MOI
> +  "structure": [],
We'll need something in the 'structure' field about what kinds of organisations are registered with this agency.

2022-04-01 08:45 UTC, kd-ods commented on lists/CI-MOI
> +  "structure": [],
And that information would also help if added to the 'description' property.

2022-04-01 08:45 UTC, kd-ods commented on lists/CI-MOI
> +    "lastUpdated": "25/3/22"
Please edit the date to be in 2022-03-25 form for clarity.

2022-04-01 08:45 UTC, kd-ods commented on lists/CI-MOI
> +    "languages": [FR]
The FR needs quotation marks around it. So:

["FR"]

2022-04-01 11:02 UTC, kd-ods commented on lists/CI-MOI
> +    "languages": [FR]
And it should be lower-case, so ["fr"]

2022-04-06 13:36 UTC, AudreyIATI commented
Changes made - let me know if you need anything else from me.

Thanks,
Audrey

2022-04-19 08:49 UTC, kd-ods approved these changes

2022-04-19 08:51 UTC, merged

2022-04-22 11:23 UTC, andylolz commented on lists/ci/ci-moi.json
> +  "url": "http://http://interieur.gouv.ci/",
There’s a typo in the URL here – `http://` is duplicated