Update es-mdj.json
org-id/register pull request #561
Opened 2024-01-12 20:30 UTC by siwhitehouse

Updated URLs as previous pages were moved without a redirect

2024-01-15 12:17 UTC, kd-ods requested changes
It doesn't look like this url http://www.mjusticia.gob.es/cs/Satellite/Portal/es/areas-tematicas/registros (which appears a few times in the entry) has been updated.

Also, the value for name.local is given as "es" whereas it should be "Ministerio de Justicia" and name.en should be "Ministry of Justice, Spain".

Could you please update the lastUpdated field too?

2024-01-19 17:10 UTC, siwhitehouse commented
> It doesn't look like this url http://www.mjusticia.gob.es/cs/Satellite/Portal/es/areas-tematicas/registros (which appears a few times in the entry) has been updated.
> 
> Also, the value for name.local is given as "es" whereas it should be "Ministerio de Justicia" and name.en should be "Ministry of Justice, Spain".
> 
> Could you please update the lastUpdated field too?

It doesn't look as though I have included any updates to the record!

2024-01-23 10:54 UTC, kd-ods requested changes
A couple of suggested edits. Otherwise this looks ready to go.

2024-01-23 10:54 UTC, kd-ods commented on lists/es/es-mdj.json
>      "en": "Ministerio de Justicia ",
```suggestion
    "en": "Ministry of Justice, Spain",

```

2024-01-23 10:54 UTC, kd-ods commented on lists/es/es-mdj.json
>      "local": "es"
```suggestion
    "local": "Ministerio de Justicia"

```

2024-01-23 18:32 UTC, siwhitehouse commented
@kd-ods Thank you - I've committed those two suggestions.

2024-01-24 09:53 UTC, kd-ods approved these changes
Great. I'll merge and update the front-end.

2024-01-24 09:55 UTC, merged