Create sz-cit.json
org-id/register pull request #571
Opened 2024-03-13 15:30 UTC by emmajclegg

New list created as per #570.

A local company has advised that this register covers both NGOs and companies, although I have only been able to find information on company registrations so far.

2024-03-14 15:54 UTC, kd-ods requested changes
Looking good, just a few things to edit.

2024-03-14 15:54 UTC, kd-ods commented on lists/sz/sz-cit.json
> +  "confirmed": false,
```suggestion
  "confirmed": true,
```
This needs to be true in order for the information to be published on the org-id website.

2024-03-14 15:54 UTC, kd-ods commented on lists/sz/sz-cit.json
> +    "company"
```suggestion
    "company",
    "charity"
```
We use 'charity' as synonymous with NGO. Not ideal, I know.

2024-03-14 15:54 UTC, kd-ods commented on lists/sz/sz-cit.json
> +    "en": "Ministry of Commerce, Industry and Trade",
```suggestion
    "en": "Ministry of Commerce, Industry and Trade, Eswatini", 
```

2024-03-14 20:38 UTC, emmajclegg commented
Thanks @kd-ods - those edits all make sense. I think I've accepted and committed them but anything else needed let me know

2024-03-15 09:41 UTC, kd-ods approved these changes

2024-03-15 09:41 UTC, merged