Create bd-nbr.json
org-id/register pull request #587
Opened 2024-09-24 11:02 UTC by HollyODSC

I have only one example registration number as this is a request from a new IATI Publisher.

2024-09-25 09:32 UTC, kd-ods requested changes
Hi @HollyODSC - just a couple of changes to make.

2024-09-25 09:32 UTC, kd-ods commented on lists/bd/bd-nbr.json
> +    "lastUpdated": "24-09-2024"
```suggestion
    "lastUpdated": "2024-09-24"
```

2024-09-25 09:32 UTC, kd-ods commented on lists/bd/bd-nbr.json
> +  "confirmed": false,
```suggestion
  "confirmed": true,
```

We set this to true at the point of submitting the PR... and treat the PR process as the final rubber stamp.

2024-10-10 10:12 UTC, kd-ods approved these changes

2024-10-10 10:13 UTC, kd-ods commented
@HollyODSC - this is looking good. Do you want to take it out of Draft and we'll get it merged?

2024-10-10 11:23 UTC, HollyODSC commented
> @HollyODSC - this is looking good. Do you want to take it out of Draft and we'll get it merged?

Thanks, I had put it in draft initially as we weren't sure whether to create it after some hoo-ha with the publisher, but it's good to go now!

2024-10-11 12:39 UTC, merged